apiVersion: v1
kind: pod
metadata:
  name: np-pod
    labels:
      app: np
spec:
  containers:
  -  name: tomcat_container
     image: tomcat:latest
     ports:
        -  name: tomcat_port
           containerPorts: 8080
---
apiVersion: v1
kind: service
metadata:
  name: np-svc
  labels: 
    app: np
spec:
 type: Nodeport
 selector:
   app: np
 ports:
 -  name: np-svc-port
    protocol: TCP
    port: 8080
    targetport: 8080
    nodePort: 30001            
